### ISSUE TITLE
Add "Speakers" to main navigation

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2015.cssconf.eu#93]

**Comment by Lucie-H** [comment]
Any particular order preferred? :) Right now I put it in last place. Maybe before team or even before sponsors?
![screen shot 2015-08-17 at 14 55 27](https://cloud.githubusercontent.com/assets/5932926/9305244/0d7fb29a-44f0-11e5-84e2-0bfeb5bb29a7.png)

**Comment by Kriesse** [comment]
@Lucie-H Good point! I think this:
Info - Speakers - Sponsors - Team - Blog
:)

**Comment by verpixelt** [comment]
Where do we wanna link at? The speakers page we have which doesn't display more than we have on the index? Or just a jump mark to the one on the index page? I'd prefer latter as long as we have no additional information on the subpage.

**Comment by Kriesse** [comment]
@verpixelt Both sounds fine to me, whatever makes more sense at the moment :)

**Comment by Lucie-H** [comment]
The page looks a bit weird because it has this header only containing background (but maybe it's on purpose?). So I'd say for now we should jump to the mark on the index page, but I don't know how exactly to that with the current navmain template. I could only add it before or after "blog" (which is linked to separately as well)

![screen shot 2015-08-17 at 17 11 16](https://cloud.githubusercontent.com/assets/5932926/9308226/2ad11ca4-4503-11e5-9c90-5af957aa369b.png)

**Comment by usefulthink** [comment]
this should resolve as we now have the speaker-details pages in place.
I agreed with @frontdevde that we should keep the overview on the homepage and just link to the detail-pages from there. A deeplink on the homepage should be enough (maybe we should consider the same for the "Team"-Link which has the same problem of not adding any additional content...
